### PR TITLE
adding search page for food info

### PR DESCRIPTION
**Pull request by andylimm0606**
I added a search page (route '/search') where you can input any type of food and get rough estimation of calories per serving + protein per serving. It's not connected to the database because i figured it can just be a page where uses can easily search for information without having to go to a different search engine. I used openAI to get nutrition information. Front and Back is connected and everything should work as intended. (page isn't pretty as it will be updated later. Core functionality is there).

must add a configuration to .env file (backend) which i will send privately through text to run.

### CODE REVIEW

**Review by jackrhines — APPROVED** [review]
looks good to me

**Comment by AryanKumar2002** [comment]
Looks good!

**Review by Ahren27 — APPROVED** [review]
Looks good! You might want to fix the format of "header:" (too many indents) in nutriSearch.js

**Review by AryanKumar2002 — APPROVED** [review]

**Comment by andylimm0606** [comment]
> Looks good! You might want to fix the format of "header:" (too many indents) in nutriSearch.js

Has been addressed

**Pull request merged**
