### PR TITLE
Profile backend

### PR DESCRIPTION
**Pull request by AryanKumar2002**
I added the profile backend to work with the profile page. If you go to /createprofile there's a UI there now so that you can input data and submit it, which will be saved in the database. Then, if you go to /profile it will display the data from the database. Currently, the UI is very bad and I will improve it, but the functionality mostly works. The only thing I still need to add is a key so that the information can be accessed for each individual user, currently the key is hardcoded. I also added a button to route to /profile.

### CODE REVIEW

**Review by jackrhines — APPROVED** [review]
It all looks good to me!  The only "issues" I saw were some spacing issues, which should be pretty easily fixable by running "npm lint-fix".  But that doesn't need to be fixed now.

**Comment by andylimm0606** [comment]
I don't see any errors on this pr. For the future, I suggest that the backend add their maintenance calorie so that we can track individual progress when adding food to show how many calories they have left. Also in your backend, the get method currently finds a user by manually inputting their Id. Instead, you can use cookies to pull in a logged-in user ID. Jack in his PR did something similar, that you can reference.

**Review by andylimm0606 — APPROVED** [review]
I don't see any errors on this pr. For the future, I suggest that the backend add their maintenance calorie so that we can track individual progress when adding food to show how many calories they have left. Also in your backend, the get method currently finds a user by manually inputting their Id. Instead, you can use cookies to pull in a logged-in user ID. Jack in his PR did something similar, that you can reference.

**Comment by nickgazdak** [comment]
Nice, I'm noticing a lot of reused code in the CSS files. in the project as a whole. This could cause some bugs later with styles getting unexpectedly overridden. We can handle that later though!

**Pull request merged**
